# Generated by Django 5.0.6 on 2025-07-07 14:13

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_data_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('file', models.FileField(upload_to='medias/%Y/%m/%d')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Не нужно, если выбран шаблон', null=True, verbose_name='Контент')),
                ('cleaned_content', models.TextField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Расписание')),
                ('percent', models.CharField(editable=False, max_length=15, verbose_name='Процент')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='Отправлено')),
                ('users', models.ManyToManyField(blank=True, related_name='ads', to='common.telegramprofile')),
                ('medias', models.ManyToManyField(blank=True, related_name='ads', to='adservice.media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
