# Generated by Django 5.0.6 on 2025-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0002_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
