# Generated by Django 5.0.6 on 2025-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0003_media_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
