# Generated by Django 5.0.6 on 2025-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0004_ad_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='language',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
