# Generated by Django 5.0.6 on 2025-01-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcode',
            name='code',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
