# Generated by Django 5.0.6 on 2025-01-26 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_textcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
