# Generated by Django 5.0.6 on 2025-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='video_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
