# Generated by Django 5.0.6 on 2025-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_data_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.CharField(blank=True, help_text='Bot username', max_length=31, null=True),
        ),
    ]
