# Generated by Django 5.0.6 on 2025-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_data_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='channel_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
