# Generated by Django 5.0.6 on 2025-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_data_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
