# Generated by Django 5.0.6 on 2025-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_telegramprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
