# Generated by Django 5.0.6 on 2026-03-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_telegramprofile_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='language',
        ),
        migrations.RemoveField(
            model_name='text',
            name='code',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TextCode',
        ),
    ]
