# Generated by Django 5.0.6 on 2026-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_text_language_remove_text_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
