# Generated by Django 5.0.6 on 2025-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
