# Generated by Django 5.0.6 on 2025-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizpart_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpart',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='corrects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='skips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='wrongs',
            field=models.IntegerField(default=0),
        ),
    ]
