# Generated by Django 5.0.6 on 2025-01-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_option_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='current_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
