# Generated by Django 5.0.6 on 2025-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userquiz_current_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpart',
            name='privacy',
        ),
        migrations.AddField(
            model_name='quiz',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
    ]
