# Generated by Django 5.0.6 on 2025-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quizpart_privacy_quiz_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
