# Generated by Django 5.0.6 on 2025-01-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='file_path',
            new_name='file_id',
        ),
    ]
