# Generated by Django 5.0.6 on 2025-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPending',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.category',),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='times',
            field=models.BigIntegerField(default=0),
        ),
    ]
