# Generated by Django 5.0.6 on 2025-04-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_data_username'),
        ('quiz', '0011_categorypending_userquiz_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('started', 'started'), ('finished', 'finished'), ('canceled', 'canceled')], default='started', max_length=31),
        ),
        migrations.CreateModel(
            name='GroupQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=63)),
                ('message_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'init'), ('started', 'started'), ('finished', 'finished'), ('canceled', 'canceled')], default='init', max_length=31)),
                ('data', models.JSONField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quizzes', to='quiz.quizpart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quizzes', to='common.telegramprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
