# Generated by Django 5.0.6 on 2025-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_userquiz_status_groupquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupquiz',
            name='skips',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupquiz',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('started', 'started'), ('finished', 'finished'), ('canceled', 'canceled'), ('paused', 'paused')], default='init', max_length=31),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('started', 'started'), ('finished', 'finished'), ('canceled', 'canceled'), ('paused', 'paused')], default='started', max_length=31),
        ),
    ]
