# Generated by Django 5.0.6 on 2025-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_groupquiz_is_answered_groupquiz_skips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='poll_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
