# Generated by Django 5.0.6 on 2025-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_groupquiz_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
