# Generated by Django 5.0.6 on 2025-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_groupquiz_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
