# Generated by Django 5.0.6 on 2025-06-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_groupquiz_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=63)),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ('-created_at',),
            },
        ),
    ]
