# Generated by Django 5.0.6 on 2025-07-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_telegramcommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramcommand',
            options={'ordering': ('order',), 'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AddField(
            model_name='telegramcommand',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
