# Generated by Django 5.0.6 on 2025-08-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_telegramcommand_options_telegramcommand_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='invite_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupquiz',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
