# Generated by Django 5.0.6 on 2025-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_groupquiz_invite_link_groupquiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='participant_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
