# Generated by Django 5.0.6 on 2025-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_groupquiz_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='language',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
