# Generated by Django 5.0.6 on 2025-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_groupquiz_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quiz/%Y/%m/%d'),
        ),
    ]
