# Generated by Django 5.0.6 on 2025-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_groupquiz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
