# Generated by Django 5.0.6 on 2025-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_quizpart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowed_users',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
