# Generated by Django 5.0.6 on 2026-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_quiz_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupquiz',
            name='language',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizpart',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
