# Generated by Django 5.0.6 on 2026-03-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_remove_groupquiz_language_alter_quiz_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allowed_users',
        ),
    ]
