# Generated by Django 5.0.6 on 2026-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_remove_quiz_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file_id',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizpart',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
