# Generated by Django 5.0.6 on 2025-01-28 21:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_data_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', ckeditor.fields.RichTextField()),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('resolved', 'resolved'), ('rejected', 'rejected')], default='pending', max_length=31)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='common.telegramprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
