# Generated by Django 5.0.6 on 2025-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
