# Generated by Django 5.0.6 on 2025-01-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='answer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='question',
            field=models.CharField(max_length=1024),
        ),
    ]
